# File Name: scripts/agent/workspace-sanitize.ps1
# Sanitizes the workspace from untracked temporary directories and files.
# Ensures perfect state isolation between runs.

$ErrorActionPreference = 'Stop'

# Define repository root
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path

Write-Host "[WORKSPACE-SANITIZE] Sanitizing workspace under: $RepoRoot" -ForegroundColor Cyan

# 1. Helper function to safely delete directories
function Remove-DirectorySafe ($dirPath) {
    if (Test-Path $dirPath -PathType Container) {
        # Check if it is a protected path
        if ($dirPath -match "([\\/]plan[\\/]|[\\/]\.agents[\\/]|[\\/]\.git[\\/]|[\\/]node_modules[\\/]|docs[\\/]LOG\.md$)") {
            Write-Host "[WARNING] Refusing to delete protected directory: $dirPath" -ForegroundColor Yellow
            return
        }
        Write-Host "[WORKSPACE-SANITIZE] Removing directory: $dirPath" -ForegroundColor Yellow
        try {
            Remove-Item -Path $dirPath -Recurse -Force -ErrorAction Stop
        } catch {
            $msg = $_.Exception.Message
            Write-Warning "Could not delete directory $dirPath : $msg"
        }
    }
}

# 2. Helper function to safely delete files
function Remove-FileSafe ($filePath) {
    if (Test-Path $filePath -PathType Leaf) {
        # Check if it is a protected path
        if ($filePath -match "([\\/]plan[\\/]|[\\/]\.agents[\\/]|[\\/]\.git[\\/]|[\\/]node_modules[\\/]|docs[\\/]LOG\.md$)") {
            Write-Host "[WARNING] Refusing to delete protected file: $filePath" -ForegroundColor Yellow
            return
        }
        Write-Host "[WORKSPACE-SANITIZE] Removing file: $filePath" -ForegroundColor Yellow
        try {
            Remove-Item -Path $filePath -Force -ErrorAction Stop
        } catch {
            $msg = $_.Exception.Message
            Write-Warning "Could not delete file $filePath : $msg"
        }
    }
}

# 3. Clean up untracked temporary directories matching data-test-*
Get-ChildItem -Path $RepoRoot -Directory -Filter "data-test-*" -Force | ForEach-Object {
    Remove-DirectorySafe $_.FullName
}

# 4. Clean up the .vitest-attachments directory (and any screenshots/pngs in it)
$vitestAttachments = Join-Path $RepoRoot ".vitest-attachments"
Remove-DirectorySafe $vitestAttachments

# 5. Clean up temporary files like .git-commit-msg.txt in repo root and subdirs (excluding protected folders)
Get-ChildItem -Path $RepoRoot -File -Filter ".git-commit-msg.txt" -Recurse -Force -ErrorAction SilentlyContinue | ForEach-Object {
    $path = $_.FullName
    if ($path -notmatch "([\\/]plan[\\/]|[\\/]\.agents[\\/]|[\\/]\.git[\\/]|[\\/]node_modules[\\/]|docs[\\/]LOG\.md$)") {
        Remove-FileSafe $path
    }
}

# 6. Clean up temporary Node/npm/yarn/pnpm debug logs
$logFilters = @("npm-debug.log*", "yarn-debug.log*", "yarn-error.log*", "lerna-debug.log*", ".pnpm-debug.log*")
foreach ($filter in $logFilters) {
    Get-ChildItem -Path $RepoRoot -File -Filter $filter -Recurse -Force -ErrorAction SilentlyContinue | ForEach-Object {
        $path = $_.FullName
        if ($path -notmatch "([\\/]plan[\\/]|[\\/]\.agents[\\/]|[\\/]\.git[\\/]|[\\/]node_modules[\\/]|docs[\\/]LOG\.md$)") {
            Remove-FileSafe $path
        }
    }
}

# 7. Clean up standard OS temporary files
$osTempFilters = @("Thumbs.db", ".DS_Store")
foreach ($filter in $osTempFilters) {
    Get-ChildItem -Path $RepoRoot -File -Filter $filter -Recurse -Force -ErrorAction SilentlyContinue | ForEach-Object {
        $path = $_.FullName
        if ($path -notmatch "([\\/]plan[\\/]|[\\/]\.agents[\\/]|[\\/]\.git[\\/]|[\\/]node_modules[\\/]|docs[\\/]LOG\.md$)") {
            Remove-FileSafe $path
        }
    }
}

# 8. Clean up coverage and nyc_output directories if they exist
Remove-DirectorySafe (Join-Path $RepoRoot "coverage")
Remove-DirectorySafe (Join-Path $RepoRoot ".nyc_output")

# 9. Auto-install Git integration hooks if in a git repository
$gitHooksDir = Join-Path $RepoRoot ".git\hooks"
if (Test-Path $gitHooksDir -PathType Container) {
    $hookContent = @"
#!/bin/sh
# Auto-generated by workspace-sanitize.ps1
powershell -NoProfile -ExecutionPolicy Bypass -File scripts/agent/workspace-sanitize.ps1
"@

    $hooksToInstall = @("pre-commit", "post-checkout", "pre-push")
    foreach ($hookName in $hooksToInstall) {
        $hookPath = Join-Path $gitHooksDir $hookName
        # Write/overwrite hook file cleanly with unix line endings (LF) to avoid shebang parsing issues in bash
        try {
            [System.IO.File]::WriteAllText($hookPath, $hookContent.Replace("`r`n", "`n"))
            Write-Host "[WORKSPACE-SANITIZE] Installed Git hook: $hookName" -ForegroundColor Green
        } catch {
            $msg = $_.Exception.Message
            Write-Warning "Could not write Git hook $hookName : $msg"
        }
    }
}

Write-Host "[WORKSPACE-SANITIZE] Workspace sanitization complete." -ForegroundColor Green
